### ISSUE TITLE
Update architecture diagrams to reflect deployment of dotmesh

### ISSUE THREAD

**Issue by deitch** [dotmesh-io/docs#60]
I find the diagram to be a bit confusing:

* Which parts are deployed?
* Do I need to deploy etcd separately?
* Why does docker talk to something _inside_ the dotmesh server, while kubernetes talks _to_ the dotmesh server?
* Are the APIs from dm client, kubernetes and docker equivalent?

Suggestion: Replace the box for “dotmesh server” with "dotmesh deployment", and expand it to include “all the parts that we deploy”. Thus, as a single box, it encompasses several components, each a circle:

* the actual dm server binary/container
* etcd
* docker volume plugin

It makes it clear that they are deployed together, and work together. This also makes "another dotmesh server" (which really is "another node in the dotmesh cluster") another parallel box with similar components.

**Comment by alaric-datamesh** [comment]
"Why does docker talk to something inside the dotmesh server, while kubernetes talks to the dotmesh server?" is just down to how it was easiest to implement it, and this diagram is intended to explain that as a fact to would-be developers who want to know what bit does what. However, the docker volume plugin, although embedded in the DM server, IS just an interface layer rather than "core" to it, so should (IMHO) be drawn somehow on the "edge" of the DM server box rather than buried deep in the heart of it.

And as for the APIs - any arrow going direct to the DM server (not the docker volume plugin) is using the DM API; then the docker volume plugin, flexvolume driver, and dynamic provisioner all provide different third-party APIs along arrows pointing at them. We could explain that on this diagram with additional arrow styles or labels, but it might clutter things - so I'd say make that difference clear if it improves the diagram, otherwise it can be left to the text.

**Comment by lukemarsden** [comment]
@petercolesdc do you think you could take a look at this please? Lower priority than the first cut of the new SaaS.

**Comment by lukemarsden** [comment]
@alaric-datamesh please also assess the diagram for CVv2-ness.

**Comment by alice-sowerby** [comment]
@lukemarsden presume this is still needed?

**Comment by lukemarsden** [comment]
Yup

**Comment by Godley** [comment]
This seems much lower prio now as dothub and dotmesh usages are not our main goal right now. Closing to clean up the engineering board (slowly), please reopen if it is needed
