### ISSUE TITLE
Finish up customer docs and port useful parts to the docs website.

### ISSUE THREAD

**Issue by prisamuel** [dotmesh-io/docs#92]
https://docs.google.com/document/d/1MCThpu4_XhCJ6ihTBs8p7TQpf6ilS_J5gUElWnHltQM/edit#

**Comment by prisamuel** [comment]
Done the first draft of docs on *everything* on https://github.com/dotmesh-io/dotscience-docs and updated customer docs. There are TODO items on stuff that can be improved. Closing this as further documentation is going to be an ongoing task.

**Comment by prisamuel** [comment]
Reopenning so that @itamarst can review the docs.

**Comment by itamarst** [comment]
Minor issues (e.g. formatting):

* [ ] Table in http://localhost:1313/setup/set-up-aws-vm/ is ASCII, not HTML.
* [ ] http://localhost:1313/setup/set-up-aws-vm/ ssh has extra backtick
* [ ] http://localhost:1313/setup/set-up-aws-vm/, http://localhost:1313/setup/,  http://localhost:1313/setup/set-up-google-cloud-vm/ links to "attach your runner" 404s
* [ ] Table in http://localhost:1313/setup/set-up-google-cloud-vm/ is ASCII
* [ ] Google CLoud VM runner page talks about running the runner, AWS VM page doesn't... they both link to same "attach runner" page though.
* [ ] http://localhost:1313/setup/expose-gpus-on-your-runner/ says "HOwever" with bad capitalization.
* [ ] In tutorials, I suggest changing the `export DOTSCIENCE_USER` to be more explicit that it's an example, not something to copy/paste. E.g. instead of USERNAME being `randomuser`, it could be `whatevervalueyoucopiedfrom`, or something...

Content suggestions:
* [ ] Given new focus on deployment, relevant tutorial descriptions in tutorial overview (Jupyter, Dotscience Python) page should explain that they cover deployment. And at start of tutorials. E.g. "In this section we'll cover Jupyter notebook-based development with Dotscience, which can be done entirely within the Jupyter environment provided within the platform." doesn't mention deployment at all. No mentions of Kubernetes, either.
* [ ] In tutorials "Script based development" is a little vague—what does that mean? And "ds is a command-line tool" doesn't add much, because it's not starting from user's use case. So maybe instead "Using Dotscience with arbitrary programs" and then introduce ds via that motivation. "If you don't want to use Jupyter, and you just want to run some pre-existing program, you can use the ds CLI to etc.".
* [ ] The glossary doesn't actually have definitions.

Misc:
* [ ] Linkcheck as part of build process?
* [ ] The "Updated" fields in the various pages seem wrong. Possibly they should be using commit timestamp, not date metadata in the page (Jekyll has plugins for this, so I assume Hugo does too).

**Comment by itamarst** [comment]
Haven't actually gone through the tutorials, but the above should improve things a bit, I think—my presumption is that goal is "get people doing something ASAP".
